
package web.wjx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoveWebServiceService", targetNamespace = "http://wjx.web/", wsdlLocation = "http://localhost:8080/LoveWebService?wsdl")
public class LoveWebServiceService
    extends Service
{

    private final static URL LOVEWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException LOVEWEBSERVICESERVICE_EXCEPTION;
    private final static QName LOVEWEBSERVICESERVICE_QNAME = new QName("http://wjx.web/", "LoveWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/LoveWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOVEWEBSERVICESERVICE_WSDL_LOCATION = url;
        LOVEWEBSERVICESERVICE_EXCEPTION = e;
    }

    public LoveWebServiceService() {
        super(__getWsdlLocation(), LOVEWEBSERVICESERVICE_QNAME);
    }

    public LoveWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOVEWEBSERVICESERVICE_QNAME, features);
    }

    public LoveWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, LOVEWEBSERVICESERVICE_QNAME);
    }

    public LoveWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOVEWEBSERVICESERVICE_QNAME, features);
    }

    public LoveWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoveWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoveWebService
     */
    @WebEndpoint(name = "LoveWebServicePort")
    public LoveWebService getLoveWebServicePort() {
        return super.getPort(new QName("http://wjx.web/", "LoveWebServicePort"), LoveWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoveWebService
     */
    @WebEndpoint(name = "LoveWebServicePort")
    public LoveWebService getLoveWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wjx.web/", "LoveWebServicePort"), LoveWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOVEWEBSERVICESERVICE_EXCEPTION!= null) {
            throw LOVEWEBSERVICESERVICE_EXCEPTION;
        }
        return LOVEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
